#include "index_html_string.h"

char resp[] = "HTTP/1.0 200 OK\r\n"
              "Server: webserver-c\r\n"
              "Content-type: text/html\r\n\r\n"
              "<html>"
              "<head>"
              "<style>"
              "/* CSS styles */"
              "body {"
              "  background-color: darkslategrey;"
              "  color: lightgray;"
              "  font-family: Arial, sans-serif;"
              "  font-size: 16px;"
              "}"
              ".container {"
              "  max-width: 800px;"
              "  margin: 0 auto;"
              "  padding: 20px;"
              "}"
              ".card {"
              "  background-color: #1f1f1f;"
              "  color: #ffffff;"
              "  margin-bottom: 20px;"
              "  padding: 20px;"
              "  border-radius: 5px;"
              "}"
              ".card h2 {"
              "  margin-top: 0;"
              "  font-size: 20px;"
              "}"
              ".card p {"
              "  margin-bottom: 10px;"
              "}"
              ".card a {"
              "  color: #ffffff;"
              "  text-decoration: none;"
              "  margin-right: 10px;"
              "}"
              ".searchBox {"
              "  width: 100%;"
              "  padding: 10px;"
              "  margin-bottom: 20px;"
              "  font-size: 16px;"
              "}"
              "</style>"
              "</head>"
              "<body>"
              "<div class=\"container\">"
              "<h1>Hi, I'm Paul.</h1>"
              "<p>A growth hacker.</p>"
              "<h2>How I can help:</h2>"
              "<ul>"
              "<li>Digital marketing and sales</li>"
              "<li>Marketing</li>"
              "<li>Organic & paid marketing + sales automation</li>"
              "<li>Content management system build and design incl. DNS and Hosting</li>"
              "<li>Web management</li>"
              "<li>CMS build and design, DNS, hosting, security & tech- seo and customization</li>"
              "<li>Software development</li>"
              "<li>Full stack (MERN) web development and app development, CI/CD</li>"
              "</ul>"
              "<h2>Projects:</h2>"
              "<div id=\"projects-sub\">"
              "<input type=\"text\" class=\"searchBox\" placeholder=\"Search projects...\">"
              "<div id=\"repos\"></div>"
              "</div>"
              "<h2>Let's grow 🌱</h2>"
              "<p>Get in touch:</p>"
              "<div class=\"links\">"
              "<a href=\"https://github.com/cunning-weasel\" target=\"_blank\">GitHub</a>"
              "<a href=\"https://www.linkedin.com/in/your-linkedin-profile\" target=\"_blank\">LinkedIn</a>"
              "<a href=\"mailto:your-email@example.com\">Email me</a>"
              "</div>"
              "</div>"
              "<script>"
              "\"use strict\";"
              "document.addEventListener('DOMContentLoaded', () => {"
              "  const searchInput = document.querySelector(\".searchBox\");"
              "  searchInput.disabled = true;"
              "  let repoList = document.querySelector(\"#repos\");"
              "  let repos = [];"
              "  searchInput.addEventListener(\"keyup\", (e) => {"
              "    const searchStr = e.target.value.toLowerCase();"
              "    const filteredRepos = repos.filter((repo) => {"
              "      return ("
              "        repo.name.toLowerCase().includes(searchStr) ||"
              "        (repo.language && repo.language.toLowerCase().includes(searchStr)) ||"
              "        (repo.description && repo.description.toLowerCase().includes(searchStr))"
              "      );"
              "    });"
              "    showRepos(filteredRepos);"
              "  });"
              "  const pullRepos = async () => {"
              "    try {"
              "      const api_url = \"https://api.github.com/users/cunning-weasel/repos\";"
              "      const res = await fetch(api_url);"
              "      repos = await res.json();"
              "      showRepos(repos);"
              "      searchInput.disabled = false;"
              "    } catch (err) {"
              "      console.error(err);"
              "    }"
              "  };"
              "  const showRepos = (repos) => {"
              "    const htmlString = repos"
              "      .map((repo) => {"
              "        return ("
              "          `<div class=\"card\">"
              "            <div class=\"card-container\">"
              "              <h2>${repo.name}</h2>"
              "            </div>"
              "            <div>"
              "              <p>${repo.language}</p>"
              "            </div>"
              "            <div>"
              "              <p>${repo.description}</p>"
              "            </div>"
              "            <div>"
              "              <a href=\"${repo.html_url}\" target=\"_blank\">Repository</a>"
              "              <a href=\"${repo.homepage}\" target=\"_blank\">Website</a>"
              "            </div>"
              "          </div>`"
              "        );"
              "      })"
              "      .join(\"\");"
              "    repoList.innerHTML = htmlString;"
              "  };"
              "  pullRepos();"
              "});"
              "</script>"
              "</body>"
              "</html>\r\n";
