#include "index_html_string.h"

char resp[] = "HTTP/1.0 200 OK\r\n"
              "Server: webserver-c\r\n"
              "Content-type: text/html; charset=utf-8\r\n\r\n"
              "<html>"
              "<head>"
              "<meta name='viewport' content='width=device-width, initial-scale=1' />"
              "<style>"
              "/* CSS styles */"
              "body {"
              "  background-color: darkslategrey;"
              "  color: lightgray;"
              "  font-family: Arial, sans-serif;"
              "  font-size: 16px;"
              "  text-align: center;"
              "}"
              ".container {"
              "  max-width: 800px;"
              "  margin: 0 auto;"
              "  padding: 20px;"
              "}"
              ".card {"
              "  background-color: #1f1f1f;"
              "  color: #ffffff;"
              "  margin-bottom: 20px;"
              "  padding: 20px;"
              "  border-radius: 5px;"
              "  transition: box-shadow 0.3s, transform 0.3s;"
              "}"
              ".card:hover {"
              "  box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);"
              "  transform: translateY(-5px);"
              "}"
              ".card h2 {"
              "  margin-top: 0;"
              "  font-size: 20px;"
              "}"
              ".card p {"
              "  margin-bottom: 10px;"
              "}"
              ".card a {"
              "  color: #ffffff;"
              "  text-decoration: none;"
              "  margin-right: 10px;"
              "}"
              ".searchBox {"
              "  width: 100%;"
              "  padding: 10px;"
              "  margin-bottom: 20px;"
              "  font-size: 16px;"
              "}"
              ".jumpButton {"
              "  display: inline-block;"
              "  padding: 10px 20px;"
              "  margin-top: 10px;"
              "  background-color: #ffffff;"
              "  color: #1f1f1f;"
              "  font-weight: bold;"
              "  text-decoration: none;"
              "  border-radius: 5px;"
              "}"
              ".links {"
              "  margin: 20px;"
              "}"
              ".links a {"
              "  display: inline-block;"
              "  margin: 10px;"
              "  background-color: #ffffff;"
              "  color: #1f1f1f;"
              "  padding: 10px 15px;"
              "  text-decoration: none;"
              "  border-radius: 5px;"
              "}"
              "@media only screen and (max-width: 600px) {"
              "  /* Mobile responsiveness */"
              "  .container {"
              "    padding: 10px;"
              "  }"
              "}"
              "</style>"
              "</head>"
              "<body>"
              "<div class=\"container\">"
              "<h1>hi, I'm Paul.</h1>"
              "<p style='padding: 1rem;'>a growth hacker.</p>"
              "<h2 style='padding: 1rem;'>how I can help:</h2>"
              "<ul style='padding: 2rem;'>"
              "<i class='fa-solid fa-code fa-beat fa-2xl'></i>"
              "<h3>software development</h3>"
              "<p style='padding-bottom: 2rem;'>full stack web & app development, CD</p>"
              "<i class='fa-solid fa-magnifying-glass-chart fa-fade fa-2xl'></i>"
              "<h3>marketing and sales</h3>"
              "<p style='padding-bottom: 2rem;'>all aspects marketing + sales automation</p>"
              "<i class='fa-solid fa-circle-nodes fa-spin fa-2xl'></i>"
              "<h3>web management</h3>"
              "<p style='padding-bottom: 2rem;'>CMS build and design, DNS, hosting, security & tech- seo and customization</p>"
              "</ul>"
              "<h2>projects:</h2>"
              "<p>open-source contribution is part of my work ethos. Feel free to take a look at some of my projects here, or jump to the contacts below👇</p>"
              "<div id=\"projects-sub\">"
              "<input type=\"text\" class=\"searchBox\" placeholder=\"Search projects...\">"
              "<button class=\"jumpButton\" onclick=\"scrollToBottom()\">Jump to bottom</button>"
              "<div id=\"repos\"></div>"
              "</div>"
              "<h2>let's grow 🌱</h2>"
              "<p>get in touch:</p>"
              "<div class=\"links\">"
              "<a href=\"https://github.com/cunning-weasel\" target=\"_blank\">GitHub 🐙</a>"
              "<a href=\"https://www.linkedin.com/in/paul-bongers\" target=\"_blank\">LinkedIn 👨‍💻</a>"
              "<a href=\"mailto:paulbongers22@gmail.com\">Email me 📤</a>"
              "</div>"
              "<p style='color:darkgray;'>{ built with vanilla c, hosted on AWS }</p>"
              "</div>"
              "<script>"
              "\"use strict\";"
              "document.addEventListener('DOMContentLoaded', () => {"
              "  const searchInput = document.querySelector(\".searchBox\");"
              "  searchInput.disabled = true;"
              "  let repoList = document.querySelector(\"#repos\");"
              "  let repos = [];"
              "  searchInput.addEventListener(\"keyup\", (e) => {"
              "    const searchStr = e.target.value.toLowerCase();"
              "    const filteredRepos = repos.filter((repo) => {"
              "      return ("
              "        repo.name.toLowerCase().includes(searchStr) ||"
              "        (repo.language && repo.language.toLowerCase().includes(searchStr)) ||"
              "        (repo.description && repo.description.toLowerCase().includes(searchStr))"
              "      );"
              "    });"
              "    showRepos(filteredRepos);"
              "  });"
              "  const pullRepos = async () => {"
              "    try {"
              "      const api_url = \"https://api.github.com/users/cunning-weasel/repos\";"
              "      const res = await fetch(api_url);"
              "      repos = await res.json();"
              "      showRepos(repos);"
              "      searchInput.disabled = false;"
              "    } catch (err) {"
              "      console.error(err);"
              "    }"
              "  };"
              "  const showRepos = (repos) => {"
              "    const htmlString = repos"
              "      .map((repo) => {"
              "        return ("
              "          `<div class=\"card\">"
              "            <div class=\"card-container\">"
              "              <h2>${repo.name}</h2>"
              "            </div>"
              "            <div>"
              "              <p>${repo.language}</p>"
              "            </div>"
              "            <div>"
              "              <p>${repo.description}</p>"
              "            </div>"
              "            <div>"
              "              <a href=\"${repo.html_url}\" target=\"_blank\">Repository</a>"
              "              <a href=\"${repo.homepage}\" target=\"_blank\">Website</a>"
              "            </div>"
              "          </div>`"
              "        );"
              "      })"
              "      .join(\"\");"
              "    repoList.innerHTML = htmlString;"
              "  };"
              "  pullRepos();"
              "});"
              "const scrollToBottom = () => {"
              "  window.scrollTo({"
              "    top: document.body.scrollHeight,"
              "    behavior: 'smooth'"
              "  });"
              "}"
              "</script>"
              "<script src='https://kit.fontawesome.com/a1922851eb.js' crossorigin='anonymous'></script>"
              "</body>"
              "</html>\r\n";